# Generated by Django 6.0.2 on 2026-09-15 14:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=2)),
                ('nome', models.CharField(max_length=100)),
                ('banheiro', models.BooleanField(default=True)),
                ('acessibilidade', models.JSONField(blank=True, default=list)),
            ],
            options={
                'verbose_name': 'Bloco',
                'verbose_name_plural': 'Blocos',
                'db_table': 'bloco',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da área contendo entre 5 e 50 caracteres.', max_length=50, validators=[django.core.validators.MinLengthValidator(5)])),
                ('capacidade', models.IntegerField(help_text='Capacidade total de ocupacao da área.')),
                ('caracteristica', models.TextField(blank=True, help_text='Descrição complementar ou características da área (opcional).', max_length=255, null=True)),
                ('disponibilidade', models.BooleanField(help_text='Indica se a área está disponível para uso/reserva.')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('MANUTENCAO', 'Manutenção'), ('INATIVO', 'Inativo')], help_text='Estado operacional da área (ATIVO, MANUTENCAO, INATIVO).', max_length=20)),
                ('tipo', models.CharField(choices=[('CONVENCIONAL', 'Convencional'), ('LABORATORIO', 'Laboratório'), ('INFORMATICA', 'Informática'), ('MUSICA', 'Música'), ('AUDITORIO', 'Auditório'), ('QUADRA', 'Quadra'), ('CHURRASQUEIRA', 'Churrasqueira')], help_text='Classificação funcional da área conforme TipoArea.', max_length=50)),
                ('equipamento', models.JSONField(blank=True, default=list, help_text='Lista de equipamentos presentes na área (choices: EquipamentoArea).')),
                ('bloco', models.ForeignKey(help_text='Relacionamento obrigatório (1..N) com a entidade Bloco.', on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='api.bloco')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'db_table': 'area',
                'unique_together': {('nome', 'bloco')},
            },
        ),
    ]
