# Generated by Django 6.0.2 on 2026-09-16 14:24

import api.validators.area_validator
import api.validators.bloco_validator
import api.validators.veiculo_validator
import django.core.validators
import django.db.models.deletion
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Código numérico do bloco contendo 1 a 2 dígitos.', max_length=2, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(2), django.core.validators.RegexValidator(re.compile('^-?\\d+\\Z'), code='invalid', message='Enter a valid integer.')])),
                ('nome', models.CharField(help_text='Nome descritivo do bloco contendo no mínimo 3 caracteres.', max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('banheiro', models.BooleanField(default=True, help_text='Indica se o bloco possúi sanitários.')),
                ('acessibilidade', models.JSONField(blank=True, default=list, help_text='Opções de acessibilidade disponíveis no bloco.', validators=[api.validators.bloco_validator.validar_acessibilidade_bloco], verbose_name=models.CharField(max_length=50))),
            ],
            options={
                'verbose_name': 'Bloco',
                'verbose_name_plural': 'Blocos',
                'db_table': 'bloco',
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Nome')),
                ('placa', models.CharField(max_length=7, unique=True, validators=[django.core.validators.MinLengthValidator(7), api.validators.veiculo_validator.validar_placa], verbose_name='Placa')),
                ('marca', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Marca')),
                ('modelo', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Modelo')),
                ('capacidade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Capacidade')),
                ('combustivel', models.CharField(max_length=20, verbose_name='Combustível')),
                ('quilometragem', models.FloatField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quilometragem')),
                ('cor', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Cor')),
                ('observacao', models.TextField(blank=True, max_length=50, null=True, verbose_name='Observação')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('MANUTENCAO', 'Manutenção'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=20, verbose_name='Status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da área contendo entre 4 e 50 caracteres.', max_length=50, validators=[django.core.validators.MinLengthValidator(4)])),
                ('capacidade', models.IntegerField(help_text='Capacidade total de ocupação da área.')),
                ('caracteristica', models.TextField(blank=True, help_text='Descrição complementar ou características da área (opcional).', max_length=300, null=True)),
                ('disponibilidade', models.BooleanField(help_text='Indica se a área está disponível para reserva.')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('MANUTENCAO', 'Manutenção'), ('INATIVO', 'Inativo')], help_text='Estado operacional da área', max_length=10)),
                ('tipo', models.CharField(choices=[('CONVENCIONAL', 'Convencional'), ('LABORATORIO', 'Laboratório'), ('INFORMATICA', 'Informática'), ('MUSICA', 'Música'), ('AUDITORIO', 'Auditório'), ('QUADRA', 'Quadra'), ('CHURRASQUEIRA', 'Churrasqueira')], help_text='Tipo de área', max_length=100)),
                ('equipamento', models.JSONField(blank=True, default=list, help_text='Equipamentos encontrados na área', validators=[api.validators.area_validator.validar_equipamentos_area], verbose_name=models.CharField(max_length=50))),
                ('bloco', models.ForeignKey(help_text='Relacionamento com Bloco obrigatório.', on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='api.bloco')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'db_table': 'area',
                'unique_together': {('nome', 'bloco')},
            },
        ),
    ]
