# Generated by Django 6.0.2 on 2026-09-15 21:38

import api.validators.area_validator
import api.validators.bloco_validator
import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Código numérico do bloco contendo 1 a 2 dígitos.', max_length=2, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(2), django.core.validators.RegexValidator(re.compile('^-?\\d+\\Z'), code='invalid', message='Enter a valid integer.')])),
                ('nome', models.CharField(help_text='Nome descritivo do bloco contendo no mínimo 3 caracteres.', max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('banheiro', models.BooleanField(default=True, help_text='Indica se o bloco possúi sanitários.')),
                ('acessibilidade', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('PISO_TATIL', 'Piso Tátil'), ('BANHEIRO', 'Banheiro Adaptado'), ('BEBEDOURO', 'Bebedouro Adaptado')], max_length=50), blank=True, default=list, help_text='Opções de acessibilidade disponíveis no bloco.', validators=[api.validators.bloco_validator.validar_acessibilidade_bloco])),
            ],
            options={
                'verbose_name': 'Bloco',
                'verbose_name_plural': 'Blocos',
                'db_table': 'bloco',
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da área contendo entre 4 e 50 caracteres.', max_length=50, validators=[django.core.validators.MinLengthValidator(4)])),
                ('capacidade', models.IntegerField(help_text='Capacidade total de ocupação da área.')),
                ('caracteristica', models.TextField(blank=True, help_text='Descrição complementar ou características da área (opcional).', max_length=300, null=True)),
                ('disponibilidade', models.BooleanField(help_text='Indica se a área está disponível para reserva.')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('MANUTENCAO', 'Manutenção'), ('INATIVO', 'Inativo')], help_text='Estado operacional da área', max_length=10)),
                ('tipo', models.CharField(choices=[('CONVENCIONAL', 'Convencional'), ('LABORATORIO', 'Laboratório'), ('INFORMATICA', 'Informática'), ('MUSICA', 'Música'), ('AUDITORIO', 'Auditório'), ('QUADRA', 'Quadra'), ('CHURRASQUEIRA', 'Churrasqueira')], help_text='Tipo de área', max_length=100)),
                ('equipamento', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('PROJETOR', 'Projetor'), ('AR_CONDICIONADO', 'Ar Condicionado'), ('QUADRO_BRANCO', 'Quadro Branco'), ('COMPUTADOR', 'Computador'), ('SISTEMA_DE_SOM', 'Sistema de Som'), ('TV', 'TV')], max_length=50), blank=True, default=list, help_text='Equipamentos encontrados na área', validators=[api.validators.area_validator.validar_equipamentos_area])),
                ('bloco', models.ForeignKey(help_text='Relacionamento com Bloco obrigatório.', on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='api.bloco')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'db_table': 'area',
                'unique_together': {('nome', 'bloco')},
            },
        ),
    ]
