# Generated by Django 6.0.2 on 2026-09-17 01:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tiporecurso_recursogeral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursogeral',
            name='nome',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='recursogeral',
            name='observacao',
            field=models.TextField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='recursogeral',
            name='quantidade_reservada',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='recursogeral',
            name='quantidade_total',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='recursogeral',
            name='tem_termo_de_responsabilidade',
            field=models.BooleanField(default=False),
        ),
    ]
