# Generated by Django 6.0.2 on 2026-09-15 16:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_veiculo_observacao_alter_veiculo_placa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='marca',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='modelo',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='nome',
            field=models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('MANUTENCAO', 'Manutenção'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=20, verbose_name='Status'),
        ),
    ]
