# Generated by Django 6.0.2 on 2026-09-26 15:44

import api.models.bloco_model
import api.validators.bloco_validator
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_recursogeral_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edupage_id', models.IntegerField(help_text='ID do período retornado pelo JSON do EduPage (ex: 1 a 15)', unique=True)),
                ('horario_inicio', models.TimeField(help_text='Hora real de início da aula')),
                ('horario_fim', models.TimeField(help_text='Hora real de término da aula')),
            ],
            options={
                'verbose_name': 'Horário Timetable',
                'verbose_name_plural': 'Horários Timetable',
                'db_table': 'horario_timetable',
            },
        ),
        migrations.CreateModel(
            name='PeriodoLetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do período letivo (ex: 2026/2)', max_length=20)),
                ('data_inicio', models.DateField(help_text='Data de início do semestre')),
                ('data_fim', models.DateField(help_text='Data de fim do semestre')),
                ('ativo', models.BooleanField(default=False, help_text='Indica se é o semestre atual/vigente')),
                ('ultima_sincronizacao', models.DateTimeField(blank=True, help_text='Data e hora da última varredura da timetable da EduPage', null=True)),
            ],
            options={
                'verbose_name': 'Período Letivo',
                'verbose_name_plural': 'Períodos Letivos',
                'db_table': 'periodo_letivo',
            },
        ),
        migrations.AddField(
            model_name='area',
            name='edupage_id',
            field=models.CharField(blank=True, help_text="ID interno da sala no JSON do EduPage (ex: '-61')", max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='capacidade',
            field=models.IntegerField(default=20, help_text='Capacidade total de ocupação da área.'),
        ),
        migrations.AlterField(
            model_name='area',
            name='disponibilidade',
            field=models.BooleanField(default=True, help_text='Indica se a área está disponível para reserva.'),
        ),
        migrations.AlterField(
            model_name='area',
            name='nome',
            field=models.CharField(help_text='Nome da área contendo entre 4 e 50 caracteres.', max_length=25, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
        migrations.AlterField(
            model_name='area',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('MANUTENCAO', 'Manutenção'), ('INATIVO', 'Inativo')], default='ATIVO', help_text='Estado operacional da área', max_length=10),
        ),
        migrations.AlterField(
            model_name='area',
            name='tipo',
            field=models.CharField(choices=[('CONVENCIONAL', 'Convencional'), ('LABORATORIO', 'Laboratório'), ('INFORMATICA', 'Informática'), ('MUSICA', 'Música'), ('AUDITORIO', 'Auditório'), ('QUADRA', 'Quadra'), ('CHURRASQUEIRA', 'Churrasqueira'), ('SALA', 'Sala')], default='SALA', help_text='Tipo de área', max_length=100),
        ),
        migrations.AlterField(
            model_name='bloco',
            name='acessibilidade',
            field=models.JSONField(blank=True, default=api.models.bloco_model.acessibilidade_default, help_text='Opções de acessibilidade disponíveis no bloco.', validators=[api.validators.bloco_validator.validar_acessibilidade_bloco], verbose_name=models.CharField(max_length=50)),
        ),
        migrations.CreateModel(
            name='CelulaTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(help_text='Nome da disciplina (vindo do EduPage)', max_length=150)),
                ('professor', models.CharField(blank=True, help_text='Nome do(s) professor(es) (opcional)', max_length=150, null=True)),
                ('turma', models.CharField(help_text='Identificação da turma', max_length=100)),
                ('dia_semana', models.CharField(choices=[('SEG', 'Segunda-feira'), ('TER', 'Terça-feira'), ('QUA', 'Quarta-feira'), ('QUI', 'Quinta-feira'), ('SEX', 'Sexta-feira'), ('SAB', 'Sábado'), ('DOM', 'Domingo')], help_text='Dia da semana da aula', max_length=20)),
                ('duracao_periodos', models.IntegerField(default=1, help_text='Quantos períodos consecutivos essa aula ocupa')),
                ('edupage_card_id', models.CharField(blank=True, help_text='ID de rastro do card original no EduPage', max_length=20, null=True)),
                ('area', models.ForeignKey(help_text='A área (sala/laboratório) onde ocorre a aula', on_delete=django.db.models.deletion.CASCADE, related_name='celulas_timetable', to='api.area')),
                ('horario', models.ForeignKey(help_text='O período/horário de início da aula', on_delete=django.db.models.deletion.PROTECT, to='api.horariotimetable')),
                ('periodo_letivo', models.ForeignKey(help_text='O semestre vigente desta aula', on_delete=django.db.models.deletion.CASCADE, related_name='celulas_timetable', to='api.periodoletivo')),
            ],
            options={
                'verbose_name': 'Célula Timetable',
                'verbose_name_plural': 'Células Timetable',
                'db_table': 'celula_timetable',
            },
        ),
    ]
