# Generated by Django 6.0.2 on 2026-09-15 19:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_veiculo_marca_alter_veiculo_modelo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='cor',
            field=models.CharField(default='Branco', max_length=20, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Cor'),
            preserve_default=False,
        ),
    ]
