# Generated by Django 6.0.2 on 2026-09-20 20:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_recursogeral_nome_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do grupo de autorização.', max_length=100, validators=[django.core.validators.MinLengthValidator(3)])),
                ('tipo_recurso_autorizado', models.CharField(choices=[('ESPACO', 'Espaço'), ('VEICULO', 'Veículo'), ('RECURSO_GERAL', 'Recurso Geral')], help_text='Tipo de recurso que o grupo está autorizado a reservar.', max_length=20)),
                ('data_inicio_validade', models.DateField(help_text='Data a partir da qual a autorização do grupo é válida.')),
                ('data_fim_validade', models.DateField(blank=True, help_text='Data de expiração da autorização do grupo (opcional).', null=True)),
                ('criador', models.ForeignKey(help_text='Usuário que criou o grupo.', on_delete=django.db.models.deletion.PROTECT, related_name='grupos_criados', to=settings.AUTH_USER_MODEL)),
                ('tipo_recurso', models.ForeignKey(blank=True, help_text='Tipo específico de Recurso Geral autorizado (ex.: bola). Obrigatório quando tipo_recurso_autorizado = RECURSO_GERAL, e deve ficar vazio nos demais casos.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='grupos_autorizados', to='api.tiporecurso')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'db_table': 'grupo',
            },
        ),
        migrations.CreateModel(
            name='GrupoAluno',
            fields=[
                ('grupo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.grupo')),
            ],
            options={
                'verbose_name': 'Grupo de Alunos',
                'verbose_name_plural': 'Grupos de Alunos',
                'db_table': 'grupo_aluno',
            },
            bases=('api.grupo',),
        ),
        migrations.CreateModel(
            name='GrupoServidor',
            fields=[
                ('grupo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.grupo')),
            ],
            options={
                'verbose_name': 'Grupo de Servidores',
                'verbose_name_plural': 'Grupos de Servidores',
                'db_table': 'grupo_servidor',
            },
            bases=('api.grupo',),
        ),
        migrations.CreateModel(
            name='MembroGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_fim_validade', models.DateField(blank=True, help_text='Data de expiração da autorização deste membro no grupo. Se vazio, vale a validade do grupo.', null=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='api.grupo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autorizacoes_grupo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membro do Grupo',
                'verbose_name_plural': 'Membros do Grupo',
                'db_table': 'membro_grupo',
                'unique_together': {('grupo', 'usuario')},
            },
        ),
    ]
