# Generated by Django 6.0.2 on 2026-09-24 03:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_recursogeral_nome_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, max_length=255, null=True, validators=[django.core.validators.MaxLengthValidator(255)], verbose_name='Descrição')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('REJEITADA', 'Rejeitada'), ('AGUARDANDO_TERMO', 'Aguardando termo'), ('CONCLUIDA', 'Concluída')], default='PENDENTE', verbose_name='Status')),
                ('data', models.DateField(verbose_name='Data')),
                ('horario_inicio', models.TimeField(verbose_name='Horário de início')),
                ('horario_fim', models.TimeField(verbose_name='Horário de fim')),
                ('duracao', models.DurationField(blank=True, editable=False, verbose_name='Duração')),
                ('tipo_reserva', models.CharField(choices=[('INTERNA', 'Interna'), ('EXTERNA', 'Externa')], verbose_name='Tipo de reserva')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to=settings.AUTH_USER_MODEL, verbose_name='Usuário criador')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
    ]
