# Generated by Django 6.0.2 on 2026-09-26 16:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_horariotimetable_periodoletivo_area_edupage_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='nome',
            field=models.CharField(help_text='Nome da área contendo entre 3 e 100 caracteres.', max_length=100, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
