# Generated by Django 6.0.2 on 2026-09-27 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaArea',
            fields=[
                ('reserva_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.reserva')),
                ('aula', models.BooleanField(default=True, verbose_name='É aula?')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='api.area', verbose_name='Área')),
            ],
            options={
                'verbose_name': 'Reserva de Área',
                'verbose_name_plural': 'Reservas de Área',
            },
            bases=('api.reserva',),
        ),
    ]
