# Generated by Django 6.0.2 on 2026-09-15 22:51

import api.validators.veiculo_validator
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_veiculo_cor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.MinLengthValidator(7), api.validators.veiculo_validator.validar_placa], verbose_name='Placa'),
        ),
    ]
