# Generated by Django 6.0.2 on 2026-09-26 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_area_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='celulatimetable',
            name='horario_fim',
            field=models.TimeField(default='00:00:00', help_text='Hora real calculada de término da aula (considerando períodos múltiplos)'),
        ),
        migrations.AddField(
            model_name='celulatimetable',
            name='horario_inicio',
            field=models.TimeField(default='00:00:00', help_text='Hora real de início da aula'),
        ),
        migrations.AlterField(
            model_name='celulatimetable',
            name='horario',
            field=models.ForeignKey(help_text='O período original no Edupage de início da aula', on_delete=django.db.models.deletion.PROTECT, to='api.horariotimetable'),
        ),
    ]
