# Generated by Django 6.0.2 on 2026-09-20 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_grupo_tipo_membro_permitido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='nome',
            field=models.CharField(help_text='Nome do grupo de autorização.', max_length=100),
        ),
    ]
