# Generated by Django 6.0.2 on 2026-09-21 00:59

import api.validators.grupo_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_grupo_nome_sem_min_length_validator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='nome',
            field=models.CharField(help_text='Nome do grupo de autorização.', max_length=100, validators=[api.validators.grupo_validator.validar_nome_grupo]),
        ),
    ]
