# Generated by Django 6.0.2 on 2026-09-27 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_reserva'),
        ('api', '0007_grupo_nome_usa_validator_proprio'),
    ]

    operations = [
    ]
