# Generated by Django 6.0.2 on 2026-09-27 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_reserva_recurso_geral'),
        ('api', '0008_merge_20260926_2154'),
    ]

    operations = [
    ]
