# Generated by Django 6.0.2 on 2026-09-28 23:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_grupo_tipo_recurso_autorizado_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaVeiculo',
            fields=[
                ('reserva_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.reserva')),
                ('destino', models.CharField(max_length=50, verbose_name='Destino')),
                ('finalidade', models.CharField(max_length=255, verbose_name='Finalidade')),
                ('quantidade_passageiros', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade de ocupantes (incluindo motorista)')),
                ('data_devolucao_prevista', models.DateField(verbose_name='Data de devolução prevista')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='api.veiculo', verbose_name='Veículo')),
            ],
            options={
                'verbose_name': 'Reserva de veículo',
                'verbose_name_plural': 'Reservas de veículos',
            },
            bases=('api.reserva',),
        ),
    ]
