# Generated by Django 6.0.2 on 2026-09-29 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_reservaarea'),
        ('api', '0010_grupo_tipo_recurso_autorizado_area'),
    ]

    operations = [
    ]
