# Generated by Django 6.0.2 on 2026-09-29 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_celulatimetable_horario_fim_and_more'),
        ('api', '0010_grupo_tipo_recurso_autorizado_area'),
    ]

    operations = [
    ]
