# Generated by Django 6.0.2 on 2026-09-29 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_merge_20260929_1241'),
        ('api', '0012_merge_20260929_1115'),
    ]

    operations = [
    ]
