# Generated by Django 6.0.2 on 2026-10-04 23:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_merge_20260929_1634'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membrogrupo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='grupo',
            name='excluido_em',
            field=models.DateTimeField(blank=True, editable=False, help_text='Data e hora da exclusão lógica. Vazio enquanto o registro está ativo.', null=True),
        ),
        migrations.AddField(
            model_name='membrogrupo',
            name='excluido_em',
            field=models.DateTimeField(blank=True, editable=False, help_text='Data e hora da exclusão lógica. Vazio enquanto o registro está ativo.', null=True),
        ),
        migrations.AddConstraint(
            model_name='membrogrupo',
            constraint=models.UniqueConstraint(condition=models.Q(('excluido_em__isnull', True)), fields=('grupo', 'usuario'), name='membro_grupo_unico_ativo'),
        ),
    ]
