# Generated by Django 6.0.2 on 2026-09-09 16:37

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Nome')),
                ('perfil_acesso', models.CharField(blank=True, max_length=12, verbose_name='Perfil de acesso')),
                ('is_active', models.BooleanField(default=False, verbose_name='Status')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Membro da equipe')),
                ('sincronizado_em', models.DateTimeField(auto_now=True, verbose_name='Última sincronização')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('system_url', models.URLField(max_length=255, verbose_name='URL do sistema')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status')),
                ('api_key', models.CharField(max_length=255, verbose_name='Chave de API')),
                ('current_state', models.CharField(default='Em desenvolvimento', max_length=20, verbose_name='Estado atual')),
                ('secret_key', models.CharField(max_length=200, verbose_name='Chave secreta')),
                ('dev_team', models.ManyToManyField(blank=True, related_name='dev_systems', to=settings.AUTH_USER_MODEL, verbose_name='Equipe DEV')),
            ],
        ),
    ]
