# Generated by Django 6.0.2 on 2026-09-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubuser',
            name='papel',
            field=models.CharField(blank=True, choices=[('admin', 'Administrador'), ('servidor', 'Servidor'), ('aluno', 'Aluno'), ('convidado', 'Convidado')], max_length=12, verbose_name='Papel'),
        ),
    ]
