# Generated by Django 6.0.2 on 2026-09-09 17:30

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nome')),
                ('system_url', models.URLField(max_length=255, verbose_name='URL do sistema')),
                ('is_active', models.BooleanField(default=True, verbose_name='Status')),
                ('api_key', models.CharField(max_length=255, verbose_name='Chave de API')),
                ('current_state', models.CharField(default='Em desenvolvimento', max_length=20, verbose_name='Estado atual')),
                ('secret_key', models.CharField(max_length=200, verbose_name='Chave secreta')),
                ('dev_team', models.ManyToManyField(blank=True, related_name='dev_systems', to=settings.AUTH_USER_MODEL, verbose_name='Equipe DEV')),
            ],
        ),
    ]
